nome = str(input('Digite seu nome completo:'))
print('Analizando seu nome ...')
print('Seu nome em maiscula e {}'.format(nome.upper()))
print('Seu nome em Minuscula e {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome) - nome.count(' ')))
print('Seu primeiro nome tem  {} letras'.format(nome.find(' ')))