nome= str(input('Digite seu nome completo:')).strip()
print('Analizando seu nome...')
print('Seu nome em maiscula e {}'.format(nome.upper()))
print('Seu nome em minusculo e {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome)-nome.count(' ')))
#print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
separa = nome.split()
print('Seu primeiro nome é {} e tem {} letras'.format(separa[0],len(separa[0])))